language: go

sudo: false

go:
  - 1.7
  - tip

install:
  - go get -u gopkg.in/resty.v0
  - go get -u github.com/golang/lint/golint
  - go get -u golang.org/x/tools/cmd/goimports


script:
- go test -v .
- go vet $(go list ./... | grep -v /vendor/)
- diff <(goimports -d $(find . -type f -name '*.go' -not -path "./vendor/*")) <(printf "")
- (for d in $(go list ./... | grep -v /vendor/); do diff <(golint $d) <(printf "") || exit 1;  done)


notifications:
  email: false
